---
version: '3.6'

networks:
  proxy:
    external: true

services:
  freqtrade:
    image: freqtradeorg/freqtrade:local
    # image: freqtradeorg/freqtrade:stable
    networks:
      - proxy

    build:
      context: .
      dockerfile: "./Dockerfile.local.dev"

    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - /etc/timezone:/etc/timezone:ro
      - /home/ubuntu/freqtrade-strategies/user_data/strategies:/freqtrade/user_data/strategies
      - /home/ubuntu/freqtrade-strategies/user_data/hyperopts:/freqtrade/user_data/hyperopts

    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    # ports:
    #  - "127.0.0.1:9090:9090"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Zeus

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
         - 'traefik.enable=true'
         - 'traefik.http.routers.freqtrade.tls=true'
         - 'traefik.http.routers.freqtrade.rule=Host(`freqtrade.dmz.golmoncrypto.com`)'
         - 'traefik.http.services.freqtrade.loadbalancer.server.port=8080'
         - 'traefik.http.middlewares.secure.basicauth.users=golmon:$$apr1$$h3yodfSK$$OYiIU44vboL3QLEumwSfK.'
         - "traefik.http.routers.freqtrade.middlewares=secure@docker"
